# Generated by Django 4.0.1 on 2022-02-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
