# Generated by Django 4.0.1 on 2022-02-07 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_myuser_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='Name',
            new_name='full_name',
        ),
    ]
