# Generated by Django 4.0.1 on 2022-02-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_myuser_full_name'),
        ('authapp', '0003_rename_name_myuser_full_name'),
    ]

    operations = [
    ]
